# Generated by Django 5.2.6 on 2025-10-10 22:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('service_type', models.CharField(default='Sunday Service', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('phone_number', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('married_status', models.CharField(choices=[('S', 'Single'), ('M', 'Married'), ('D', 'Divorced'), ('B', 'Bereaved')], default='S', max_length=1)),
                ('home_address', models.CharField(max_length=200)),
                ('occupation', models.CharField(max_length=200)),
                ('place_of_work', models.CharField(max_length=200)),
                ('church_membership_status', models.CharField(choices=[('M', 'Member'), ('D', 'Deacon'), ('S', 'Deaconess'), ('E', 'Elder'), ('P', 'Pastor')], default='M', max_length=1)),
                ('ministry', models.CharField(choices=[('C', 'Children'), ('Y', 'Youth'), ('E', 'Evangelism'), ('P', 'Pemem'), ('W', 'Women')], default='Y', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='api.attendancerecord')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='api.members')),
            ],
        ),
    ]
