# Generated by Django 5.2.6 on 2025-11-08 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='phone_number',
            field=models.IntegerField(max_length=20),
        ),
    ]
