# Generated by Django 5.2.6 on 2025-11-08 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_members_middle_name_alter_members_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='members',
            options={'verbose_name_plural': 'Members'},
        ),
        migrations.AlterField(
            model_name='members',
            name='church_membership_status',
            field=models.CharField(choices=[('M', 'Member'), ('V', 'Visitor'), ('N', 'New Convert')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='members',
            name='home_address',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='members',
            name='married_status',
            field=models.CharField(choices=[('S', 'Single'), ('M', 'Married'), ('D', 'Divorced'), ('W', 'Widowed')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='members',
            name='ministry',
            field=models.CharField(choices=[('Y', 'Youth'), ('C', 'Children'), ('W', 'Women'), ('M', 'Men'), ('U', 'Usher'), ('O', 'Other')], default='Y', max_length=1),
        ),
        migrations.AlterField(
            model_name='members',
            name='occupation',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='members',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='members',
            name='place_of_work',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='members',
            unique_together={('first_name', 'last_name', 'middle_name')},
        ),
    ]
