# Generated by Django 5.2.6 on 2025-11-13 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_members_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='members',
            unique_together=set(),
        ),
    ]
